include:
  - board: nice_nano_v2
    shield: anywhy_flake_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: anywhy_flake_right
  - board: nice_nano_v2
    shield: settings_reset
